# Site settings
title: Kritika Buttan
name: Kritika Buttan

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/kritika-buttan-3b98101a/

#Any buzzword skills you want to include
skills:
 - Scala
 - Akka-http
 - Microservices
 - Slick
 - Product management
 - API design
 - Groovy
 - Spring MVC/Boot/Social
 - Gradle
 - Java
 - JPA
 - SQL
 - REST
 - Technical Architecture
 - Machine learning

#Work experience is required
roles:
 - title: Scrum Master
   start: 2018
   end: Ongoing
   employer: DXC Technologies
   description: Automation of Server Lifecycle Management - DevOps Tools
 - title: Team Lead
   start: 2016
   end: 2017
   employer: CSC Technologies
   description: Work Primarily with Asset Risk Management Team Projects based on the Agile Manifesto and Methodology.
 - title: Application development and support
   start: 2012
   end: 2015
   employer: CSC Technologies
   description:	Working mainly on development and architecture work using HPAM and interface tools.
 - title: Application development and support
   start: 2010
   end: 2012
   employer: CSC Technologies
   description: Working on Administrative and Tailoring part, Form Designing, format and Link Control as per customer requirement.

#Education is required
education:
 - level: Post Graduation Diploma in Information Technology (PGDIT)
   date: 2012
   subject: Information Technology
   school: Symbiosis Centre of Distance Learning, Pune. India
   
 - level: Bachelor of Technology (B.Tech.)
   date: 2009
   subject: Information Technology
   school: Guru Gobind Singh Indraprastha University, Delhi. India
   
 Certification: |
    •	ITIL V3 foundation – March 2011 <br/><br/>
    •	HP Service Manager 7.11. – May 2011 <br/><br/>
    •	HP Asset Manager 9.x – January 2016 <br/><br/>
    •	Oracle SQL Certification 1Z0-047 – Dec 2012 <br/><br/>
    •	Agile Certification – January 2018 <br/><br/>
    •	Certified Scrum Master – March 2018 <br/><br/>
    •	Certified Associate in Project Management – April 2018. <br/><br/>


intro: |
  •	Over 9 years of experience in Leading the Development and deployment of Automation Tools- HPAM, Service Now, Universal Configuration Management system (UCMDB), Universal Discovery, Connect IT and HPSM, Agile-Scrum Master and SAFe Agile Framework. Over 4 years of experience in Project Handling and Team Co-ordination. 6 Months of Onsite Experience. <br/><br/>
  •	Have good exposure to IT Service Management and IT Asset Management domain with Agile Methodology and Scrum Framework. In Depth knowledge of SAFe Agile principles and Scrum Master Responsibilities. <br/><br/>
  •	Good understanding of client’s business, current system and technical requirements and have good knowledge of the SDLC, Agile-Scrum Master Projects and quality processes in projects and also possess good inter personal, communication and presentation skills apart from being analytical thinker and quick learner.<br/><br/>
  •	Excellent understanding of Clients’ managerial decision-making needs, report requirements and the technical data and management reports required to fulfill these requirements and also capable of working independently in challenging environment with minimal support. <br/><br/>
  •	Also Understanding of the Scrum Master Values, Scrum Empirical Process and the project methodology. Knowledge of Various Modules in the Jira Tools and Deployment of Automation Tools. <br/><br/>
