# Site settings
title: Kritika Buttan
name: Kritika Buttan

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/kritika-buttan-3b98101a/

#Any buzzword skills you want to include
skills:
 - Agile
 - Scrum

#Work experience is required
roles:
 - title: CTO
   start: 2017
   end: Ongoing
   employer: Basement Crowd
   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.
 - title: Senior Engineer
   start: 2016
   end: 2017
   employer: Emerald Street Ventures
   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
 - title: Senior Engineer
   start: 2012
   end: 2016
   employer: Covestor
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
 - title: Associate Manager
   start: 2005
   end: 2012
   employer: Accenture
   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2003
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham

#This section is optional (as is the image link below)

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#List of interesting Github repo/projects to include - optional
#Stackoverflow flair is optional

intro: |
  •	Over 9 years of experience in Leading the Development and deployment of Automation Tools- HPAM, Service Now, Universal Configuration Management system (UCMDB), Universal Discovery, Connect IT and HPSM, Agile-Scrum Master and SAFe Agile Framework. Over 4 years of experience in Project Handling and Team Co-ordination. 6 Months of Onsite Experience.<br/><br/>
  •	Have good exposure to IT Service Management and IT Asset Management domain with Agile Methodology and Scrum Framework. In Depth knowledge of SAFe Agile principles and Scrum Master Responsibilities. <br/><br/>
  •	Good understanding of client’s business, current system and technical requirements and have good knowledge of the SDLC, Agile-Scrum Master Projects and quality processes in projects and also possess good inter personal, communication and presentation skills apart from being analytical thinker and quick learner.<br/><br/>
  •	Excellent understanding of Clients’ managerial decision-making needs, report requirements and the technical data and management reports required to fulfill these requirements and also capable of working independently in challenging environment with minimal support. <br/><br/>
  •	Also Understanding of the Scrum Master Values, Scrum Empirical Process and the project methodology. Knowledge of Various Modules in the Jira Tools and Deployment of Automation Tools. <br/><br/>
  
additionalinfo: |
   
 Certification: -
     •	ITIL V3 foundation – March 2011
     •	HP Service Manager 7.11. – May 2011
     •	HP Asset Manager 9.x – January 2016
     •	Oracle SQL Certification 1Z0-047 – Dec 2012
     •	Agile Certification – January 2018
     •	Certified Scrum Master – March 2018
     •	Certified Associate in Project Management – April 2018.


